const lessons={
 pormal:{tag:'PORMAL • PAMANTAYAN AT SINING',title:'Pambansa at Panitikan',body:`<p>Ginagamit ang <strong>pambansang antas</strong> sa edukasyon, pamahalaan, midya, at iba pang opisyal na komunikasyon. Ito ang malawak na nauunawaan at sinusunod na pamantayan.</p><p>Ang <strong>panitikan</strong> naman ay masining, malikhain, at maaaring matalinghaga. Makikita ito sa tula, nobela, sanaysay, at talumpating pampanitikan.</p><h3>Pagkakaiba sa kilos</h3><div class="example"><b>Pambansa:</b> “Mahalagang pangalagaan ang ating mga likas na yaman.”</div><div class="example"><b>Panitikan:</b> “Ang kagubatan ang hininga ng lupang sinilangan.”</div><div class="challenge"><strong>Hamon:</strong> Sa research presentation, pambansa ang pangunahing antas. Maaaring gumamit ng panitikan sa pamagat o pambungad kung angkop sa layunin.</div>`},
 barayti:{tag:'LUGAR • PANGKAT • IDENTIDAD',title:'Lalawiganin at Barayti',body:`<p>Ang <strong>lalawiganin</strong> ay mga salitang ginagamit sa isang tiyak na rehiyon o pamayanan. Maaari itong may natatanging bokabularyo, punto, o paraan ng pagbuo ng pangungusap.</p><p>Mas malawak dito ang konsepto ng <strong>barayti ng wika</strong>: nagkakaroon ng baryasyon dahil sa heograpiya, pangkat panlipunan, propesyon, edad, o mismong sitwasyon.</p><h3>Hindi “maling Filipino”</h3><div class="example">Ang lokal na salita ay may sariling sistemang panlingguwistika at dalang kasaysayan. Kapag hindi ito nauunawaan ng lahat, magbigay ng katumbas o paliwanag.</div><div class="challenge"><strong>Hamon:</strong> Sa panayam sa komunidad, panatilihin ang orihinal na lokal na salita sa sipi at ipaliwanag ang kahulugan nito para sa mas malawak na mambabasa.</div>`},
 impormal:{tag:'ARAW-ARAW • BARKADA • DIGITAL',title:'Kolokyal at Balbal',body:`<p>Ang <strong>kolokyal</strong> ay natural na wikang ginagamit sa pang-araw-araw na usapan. Madalas itong pinaikli: “sandali” → “saglit/teka,” o “kumusta” → “musta.”</p><p>Ang <strong>balbal</strong> ay salitang nabubuo sa mga tiyak na pangkat o subkultura. Malikhaing-malikhaing ito at mabilis magbago, lalo na online.</p><h3>Angkop, hindi awtomatikong mali</h3><div class="example"><b>Sa group chat:</b> “Pre, send mo naman ’yung notes.”<br><b>Sa propesor:</b> “Magandang araw po. Maaari ko po bang hingin ang kopya ng lecture notes?”</div><div class="challenge"><strong>Hamon:</strong> Iisang layunin, magkaibang kausap. Ang mahusay na tagapagsalita ay marunong magpalit ng antas nang hindi nawawala ang mensahe.</div>`}
};
const quiz=[
 {s:'Email sa propesor',q:'Alin ang pinakaangkop na pambungad?',a:['Uy Prof, may tanong ako.','Magandang araw po, Propesor. Nais ko pong linawin…','Lodi, pa-clarify naman.','Ano ba kasi ito?'],c:1,e:'Pormal at magalang angkop sa akademikong komunikasyon.'},
 {s:'Tula para sa klase',q:'Anong antas ang nangingibabaw sa linyang “Humahalik ang liwanag sa tahimik na dagat”?',a:['Pambansa','Panitikan','Kolokyal','Balbal'],c:1,e:'Masining at matalinghaga ang pahayag, kaya panitikan.'},
 {s:'Usapang magkakaibigan',q:'“Teka lang, parating na ako.” Ito ay halimbawa ng…',a:['Kolokyal','Panitikan','Teknikal','Pambansa lamang'],c:0,e:'Natural at pinaikling anyo ito sa pang-araw-araw na usapan.'},
 {s:'Panayam sa komunidad',q:'May lokal na salitang hindi alam ng mambabasa. Ano ang pinakamainam?',a:['Tanggalin agad ang salita','Tawaging maling Filipino','Panatilihin at lagyan ng paliwanag','Palitan lahat ng balbal'],c:2,e:'Napananatili nito ang identidad habang nagiging malinaw sa mas malawak na mambabasa.'},
 {s:'Research paper',q:'Alin ang dapat iwasan sa pangunahing talakay?',a:['Malinaw na terminolohiya','Mga sanggunian','Hindi ipinaliwanag na balbal','Pambansang antas'],c:2,e:'Maaaring malabo at hindi angkop ang di-ipinaliwanag na balbal sa akademikong teksto.'},
 {s:'Online community',q:'Bakit mabilis magbago ang mga salitang balbal?',a:['Bawal ang mga ito','Nakaugnay sa malikhaing gamit ng pangkat at uso','Iisa lamang ang kahulugan nila','Ginagamit lang sa aklat'],c:1,e:'Hinuhubog ang balbal ng pangkat, uso, at mabilis na palitan online.'},
 {s:'Dalawang magkaibang kausap',q:'Ano ang tawag sa sadyang pagpapalit ng paraan ng pagsasalita ayon sa kausap o sitwasyon?',a:['Paglimot sa wika','Pag-aangkop o code-switching','Maling gramatika','Pagsasalin lamang'],c:1,e:'Ang pag-aangkop—at kung wika ang pinapalitan, code-switching—ay estratehiyang komunikatibo.'},
 {s:'Pangkalahatang prinsipyo',q:'Paano pinakamahusay sinusuri ang antas ng wika?',a:['Kung alin ang pinakamahabang salita','Kung alin ang pinakamoderno','Kung angkop sa kausap, layunin, lugar, at daluyan','Kung purong Filipino lamang'],c:2,e:'Ang konteksto ang sentro ng mahusay at responsableng pagpili ng wika.'}
];
const dialog=document.querySelector('#lessonDialog'),content=document.querySelector('#dialogContent');
document.querySelectorAll('.lesson-card').forEach(b=>b.addEventListener('click',()=>{const l=lessons[b.dataset.lesson];content.innerHTML=`<article class="dialog-inner"><span class="tag">${l.tag}</span><h2>${l.title}</h2>${l.body}</article>`;dialog.showModal()}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
let index=0,score=0,chosen=false;const count=document.querySelector('#quizCount'),bar=document.querySelector('#progressBar'),scenario=document.querySelector('#scenario'),question=document.querySelector('#question'),answers=document.querySelector('#answers'),feedback=document.querySelector('#feedback'),next=document.querySelector('#nextBtn');
function renderQuestion(){chosen=false;next.disabled=true;feedback.textContent='';const item=quiz[index];count.textContent=`Tanong ${index+1} sa ${quiz.length}`;bar.style.width=`${(index+1)/quiz.length*100}%`;scenario.textContent=item.s;question.textContent=item.q;answers.innerHTML='';item.a.forEach((x,i)=>{const b=document.createElement('button');b.className='answer';b.innerHTML=`<span class="key">${String.fromCharCode(65+i)}</span><span>${x}</span>`;b.addEventListener('click',()=>selectAnswer(i,b));answers.appendChild(b)})}
function selectAnswer(i,b){if(chosen)return;chosen=true;const item=quiz[index];document.querySelectorAll('.answer').forEach((x,j)=>{x.disabled=true;if(j===item.c)x.classList.add('correct')});if(i===item.c){score++;feedback.innerHTML=`<strong>Tama.</strong> ${item.e}`}else{b.classList.add('wrong');feedback.innerHTML=`<strong>Hindi pa.</strong> ${item.e}`}next.disabled=false;document.querySelector('#scorePreview').textContent=score}
function showResult(){document.querySelector('#quizCard').hidden=true;const card=document.querySelector('#resultCard');card.hidden=false;document.querySelector('#finalScore').textContent=score;const pct=score/quiz.length;document.querySelector('#resultTitle').textContent=pct>=.875?'Mahusay kang bumasa ng konteksto!':pct>=.625?'Maganda ang pundasyon mo.':'Balikan natin ang mga module.';document.querySelector('#resultText').textContent=pct>=.875?'Kaya mong iugnay ang antas ng wika sa tunay na sitwasyong komunikatibo.':pct>=.625?'Malinaw na sa iyo ang karamihan ng konsepto. Balikan ang paliwanag sa mga tanong na hindi nakuha.':'I-click muli ang mga larawang-aralin at ituon ang pansin sa kausap, layunin, lugar, at daluyan.';card.scrollIntoView({behavior:'smooth',block:'center'})}
next.addEventListener('click',()=>{index++;index<quiz.length?renderQuestion():showResult()});document.querySelector('#restartBtn').addEventListener('click',()=>{index=0;score=0;document.querySelector('#scorePreview').textContent='—';document.querySelector('#resultCard').hidden=true;document.querySelector('#quizCard').hidden=false;renderQuestion()});
const menu=document.querySelector('.menu'),links=document.querySelector('.nav-links');menu.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',open)});links.addEventListener('click',()=>{links.classList.remove('open');menu.setAttribute('aria-expanded','false')});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));renderQuestion();
if(document.modelContext?.registerTool){const ac=new AbortController();Promise.resolve(document.modelContext.registerTool({name:'start_antas_ng_wika_quiz',title:'Simulan ang pagsusulit',description:'Buksan at i-reset ang pagsusulit tungkol sa Antas ng Wika.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){index=0;score=0;document.querySelector('#scorePreview').textContent='—';document.querySelector('#resultCard').hidden=true;document.querySelector('#quizCard').hidden=false;renderQuestion();document.querySelector('#pagsusulit').scrollIntoView();return{status:'started',questions:quiz.length}}},{signal:ac.signal})).catch(()=>{})}
